/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ChatRoomIdIndexRouteImport } from './routes/chat/$roomId/index'
import { Route as MyEditIndexRouteImport } from './routes/my/edit/index'
import { Route as PotsPotIdIndexRouteImport } from './routes/pots/$potId/index'
import { Route as PotsNewIndexRouteImport } from './routes/pots/new/index'
import { Route as PotsPotIdEditIndexRouteImport } from './routes/pots/$potId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomIdIndexRoute = ChatRoomIdIndexRouteImport.update({
  id: '/chat/$roomId/',
  path: '/chat/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEditIndexRoute = MyEditIndexRouteImport.update({
  id: '/my/edit/',
  path: '/my/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const PotsPotIdIndexRoute = PotsPotIdIndexRouteImport.update({
  id: '/pots/$potId/',
  path: '/pots/$potId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PotsNewIndexRoute = PotsNewIndexRouteImport.update({
  id: '/pots/new/',
  path: '/pots/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PotsPotIdEditIndexRoute = PotsPotIdEditIndexRouteImport.update({
  id: '/pots/$potId/edit/',
  path: '/pots/$potId/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/': typeof ChatIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my/': typeof MyIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/chat/$roomId/': typeof ChatRoomIdIndexRoute
  '/my/edit/': typeof MyEditIndexRoute
  '/pots/$potId/': typeof PotsPotIdIndexRoute
  '/pots/new/': typeof PotsNewIndexRoute
  '/pots/$potId/edit/': typeof PotsPotIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatIndexRoute
  '/login': typeof LoginIndexRoute
  '/my': typeof MyIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/chat/$roomId': typeof ChatRoomIdIndexRoute
  '/my/edit': typeof MyEditIndexRoute
  '/pots/$potId': typeof PotsPotIdIndexRoute
  '/pots/new': typeof PotsNewIndexRoute
  '/pots/$potId/edit': typeof PotsPotIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/': typeof ChatIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my/': typeof MyIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/chat/$roomId/': typeof ChatRoomIdIndexRoute
  '/my/edit/': typeof MyEditIndexRoute
  '/pots/$potId/': typeof PotsPotIdIndexRoute
  '/pots/new/': typeof PotsNewIndexRoute
  '/pots/$potId/edit/': typeof PotsPotIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat/'
    | '/login/'
    | '/my/'
    | '/onboarding/'
    | '/chat/$roomId/'
    | '/my/edit/'
    | '/pots/$potId/'
    | '/pots/new/'
    | '/pots/$potId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/chat/$roomId'
    | '/my/edit'
    | '/pots/$potId'
    | '/pots/new'
    | '/pots/$potId/edit'
  id:
    | '__root__'
    | '/'
    | '/chat/'
    | '/login/'
    | '/my/'
    | '/onboarding/'
    | '/chat/$roomId/'
    | '/my/edit/'
    | '/pots/$potId/'
    | '/pots/new/'
    | '/pots/$potId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MyIndexRoute: typeof MyIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ChatRoomIdIndexRoute: typeof ChatRoomIdIndexRoute
  MyEditIndexRoute: typeof MyEditIndexRoute
  PotsPotIdIndexRoute: typeof PotsPotIdIndexRoute
  PotsNewIndexRoute: typeof PotsNewIndexRoute
  PotsPotIdEditIndexRoute: typeof PotsPotIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomId/': {
      id: '/chat/$roomId/'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId/'
      preLoaderRoute: typeof ChatRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/edit/': {
      id: '/my/edit/'
      path: '/my/edit'
      fullPath: '/my/edit/'
      preLoaderRoute: typeof MyEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pots/$potId/': {
      id: '/pots/$potId/'
      path: '/pots/$potId'
      fullPath: '/pots/$potId/'
      preLoaderRoute: typeof PotsPotIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pots/new/': {
      id: '/pots/new/'
      path: '/pots/new'
      fullPath: '/pots/new/'
      preLoaderRoute: typeof PotsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pots/$potId/edit/': {
      id: '/pots/$potId/edit/'
      path: '/pots/$potId/edit'
      fullPath: '/pots/$potId/edit/'
      preLoaderRoute: typeof PotsPotIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MyIndexRoute: MyIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ChatRoomIdIndexRoute: ChatRoomIdIndexRoute,
  MyEditIndexRoute: MyEditIndexRoute,
  PotsPotIdIndexRoute: PotsPotIdIndexRoute,
  PotsNewIndexRoute: PotsNewIndexRoute,
  PotsPotIdEditIndexRoute: PotsPotIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
